// Created by iWeb 3.0.4 local-build-20161102

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,656),url:'Contact_Us_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Contact_Us_files/stroke_1.png'},{rect:new IWRect(1,-1,650,2),url:'Contact_Us_files/stroke_2.png'},{rect:new IWRect(651,-1,2,2),url:'Contact_Us_files/stroke_3.png'},{rect:new IWRect(651,1,2,656),url:'Contact_Us_files/stroke_4.png'},{rect:new IWRect(651,657,2,2),url:'Contact_Us_files/stroke_5.png'},{rect:new IWRect(1,657,650,2),url:'Contact_Us_files/stroke_6.png'},{rect:new IWRect(-1,657,2,2),url:'Contact_Us_files/stroke_7.png'}],new IWSize(652,658)),stroke_3:new IWStrokeParts([{rect:new IWRect(-2,1,3,86),url:'Contact_Us_files/stroke_24.png'},{rect:new IWRect(-2,-2,3,3),url:'Contact_Us_files/stroke_25.png'},{rect:new IWRect(1,-2,196,3),url:'Contact_Us_files/stroke_26.png'},{rect:new IWRect(197,-2,3,3),url:'Contact_Us_files/stroke_27.png'},{rect:new IWRect(197,1,3,86),url:'Contact_Us_files/stroke_28.png'},{rect:new IWRect(197,87,3,3),url:'Contact_Us_files/stroke_29.png'},{rect:new IWRect(1,87,196,4),url:'Contact_Us_files/stroke_30.png'},{rect:new IWRect(-2,87,3,3),url:'Contact_Us_files/stroke_31.png'}],new IWSize(199,89)),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,1,3,86),url:'Contact_Us_files/stroke_16.png'},{rect:new IWRect(-2,-2,3,3),url:'Contact_Us_files/stroke_17.png'},{rect:new IWRect(1,-2,200,3),url:'Contact_Us_files/stroke_18.png'},{rect:new IWRect(201,-2,3,3),url:'Contact_Us_files/stroke_19.png'},{rect:new IWRect(201,1,3,86),url:'Contact_Us_files/stroke_20.png'},{rect:new IWRect(201,87,3,3),url:'Contact_Us_files/stroke_21.png'},{rect:new IWRect(1,87,200,4),url:'Contact_Us_files/stroke_22.png'},{rect:new IWRect(-2,87,3,4),url:'Contact_Us_files/stroke_23.png'}],new IWSize(203,89)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,242),url:'Contact_Us_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Contact_Us_files/stroke_9.png'},{rect:new IWRect(2,-2,358,4),url:'Contact_Us_files/stroke_10.png'},{rect:new IWRect(360,-2,4,4),url:'Contact_Us_files/stroke_11.png'},{rect:new IWRect(360,2,4,242),url:'Contact_Us_files/stroke_12.png'},{rect:new IWRect(360,244,4,4),url:'Contact_Us_files/stroke_13.png'},{rect:new IWRect(2,244,358,4),url:'Contact_Us_files/stroke_14.png'},{rect:new IWRect(-2,244,4,4),url:'Contact_Us_files/stroke_15.png'}],new IWSize(362,246))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Contact_Us_files/Contact_UsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');fixAllIEPNGs('Media/transparent.gif');Widget.onload();applyEffects()}
function onPageUnload()
{Widget.onunload();}
